export const GET_MARKERS = "GET_MARKERS"
export const DELETE_MARKERS = "DELETE_MARKERS"
export const FILTER_BY_TYPE= "FILTER_BY_TYPE"
export const SET_OPEN= "SET_OPEN"
export const OPEN_LATERL_LIST= "OPEN_LATERL_LIST"
export const OPEN_MODIFY_PANEL= "OPEN_MODIFY_PANEL"
export const PUT_MARKER= "PUT_MARKER"
export const GET_DETAILS= "GET_DETAILS"
export const CHANGE_MAP= "CHANGE_MAP"
export const GET_USERS= "GET_USERS"
export const MODIFY_USER= "MODIFY_USER"
export const POST_USER= "POST_USER"
export const ADMIN= "ADMIN"


